[program:keuangan-bot]
process_name=%(program_name)s
command=/home/ubuntu/keuangan-bot/venv/bin/python /home/ubuntu/keuangan-bot/bot.py
directory=/home/ubuntu/keuangan-bot
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/home/ubuntu/keuangan-bot/logs/bot.log
stderr_logfile=/home/ubuntu/keuangan-bot/logs/bot-error.log
environment=PYTHONUNBUFFERED=1
